# Generated by Django 5.2.7 on 2025-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('rating', models.FloatField(default=0)),
                ('wifi', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='studyspaces/')),
            ],
        ),
    ]
