# Generated by Django 5.2.7 on 2025-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('wifi_available', models.BooleanField(default=False)),
                ('has_outlets', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('air_conditioned', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='study_spaces/')),
            ],
        ),
    ]
