# Generated by Django 5.2.7 on 2025-10-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studyspot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyspot',
            old_name='has_outlets',
            new_name='ac',
        ),
        migrations.RenameField(
            model_name='studyspot',
            old_name='air_conditioned',
            new_name='coffee',
        ),
        migrations.RenameField(
            model_name='studyspot',
            old_name='wifi_available',
            new_name='free',
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='is_free',
        ),
        migrations.AddField(
            model_name='studyspot',
            name='location',
            field=models.CharField(default=3.0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyspot',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyspot',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studyspots/'),
        ),
    ]
