# Generated by Django 5.2.7 on 2025-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_has_outlets_studyspot_ac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
