# Generated by Django 5.2.6 on 2025-10-26 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studyspot_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('government_id', models.FileField(blank=True, null=True, upload_to='staff_docs/ids/')),
                ('study_place_name', models.CharField(max_length=150)),
                ('study_place_address', models.CharField(max_length=255)),
                ('study_place_website', models.URLField(blank=True, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('proof_of_ownership', models.FileField(blank=True, null=True, upload_to='staff_docs/ownership/')),
                ('role_description', models.CharField(help_text='e.g., Manager, Representative', max_length=100)),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='staff_docs/address/')),
                ('social_media_links', models.TextField(blank=True, help_text='Optional: links separated by commas', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
