# Generated by Django 5.2.6 on 2025-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_staffapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='government_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='proof_of_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='proof_of_ownership',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='role_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='social_media_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
