# Generated by Django 5.2.6 on 2025-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_staffapplication_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
