# Generated by Django 5.2.6 on 2025-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_is_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='open_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='outlets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='pastries',
            field=models.BooleanField(default=False),
        ),
    ]
