# Generated by Django 5.2.7 on 2025-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studyspot_open_24_7_studyspot_outlets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
