# Generated by Django 5.2.7 on 2025-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='rating',
        ),
        migrations.AddField(
            model_name='studyspot',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
